from flask import Flask, render_template, request, jsonify, redirect, url_for
import pandas as pd
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

# Load your data from the CSV file
data = pd.read_csv("processedData.csv", encoding='utf-8')

@app.route("/")
def home():
    conditions = [
"Abnormal Uterine Bleeding" ,
 "Abortion" ,
 "Acetaminophen Overdose" ,
 "acial Lipoatrophy" ,
 "acial Wrinkles" ,
 "Acne" ,
 "Actinic Keratosis" ,
 "actor IX Deficiency" ,
 "Acute Coronary Syndrome" ,
 "Acute Lymphoblastic Leukemia" ,
 "Acute Nonlymphocytic Leukemia" ,
 "Acute Otitis Externa" ,
 "Acute Promyelocytic Leukemia" ,
 "Addison's Disease" ,
 "ADHD" ,
 "Adrenocortical Insufficiency" ,
 "Adult Human Growth Hormone Deficiency" ,
 "Agitated State" ,
 "Agitation" ,
 "AIDS Related Wasting" ,
 "Alcohol Dependence" ,
 "Alcohol Withdrawal" ,
 "Allergic Reactions" ,
 "Allergic Rhinitis" ,
 "Allergic Urticaria" ,
 "Allergies" ,
 "Alopecia" ,
 "Alpha-1 Proteinase Inhibitor Deficiency" ,
 "Alzheimer's Disease" ,
 "Amebiasis" ,
 "Amenorrhea" ,
 "amilial Cold Autoinflammatory Syndrome" ,
 "Anal Fissure and Fistula" ,
 "Anal Itching" ,
 "Anaplastic Astrocytoma" ,
 "Androgenetic Alopecia" ,
 "Anemia" ,
 "Anemia Associated with Chronic Renal Failure" ,
 "Anemia, Chemotherapy Induced" ,
 "Anemia, Sickle Cell" ,
 "Anesthesia" ,
 "Angina" ,
 "Angina Pectoris Prophylaxis" ,
 "Ankylosing Spondylitis" ,
 "Anorexia" ,
 "Anthrax" ,
 "Antiphospholipid Syndrome" ,
 "Anxiety" ,
 "Anxiety and Stress" ,
 "Aphthous Ulce" ,
 "Aplastic Anemia" ,
 "Arrhythmia" ,
 "Asperger Syndrome" ,
 "Aspergillosis, Aspergilloma" ,
 "Asthma" ,
 "Asthma, acute" ,
 "Asthma, Maintenance" ,
 "atigue" ,
 "Atopic Dermatitis" ,
 "Atrial Fibrillation" ,
 "Atrial Flutte" ,
 "Atrophic Urethritis" ,
 "Atrophic Vaginitis" ,
 "Auditory Processing Disorde" ,
 "Autism" ,
 "Autoimmune Hemolytic Anemia" ,
 "Autoimmune Hepatitis" ,
 "B12 Nutritional Deficiency" ,
 "Back Pain" ,
 "Bacteremia" ,
 "Bacterial Endocarditis Prevention" ,
 "Bacterial Infection" ,
 "Bacterial Skin Infection" ,
 "Bacterial Vaginitis" ,
 "Barrett's Esophagus" ,
 "Basal Cell Carcinoma" ,
 "Behcet's Disease" ,
 "Benign Essential Trem" ,
 "Benign Prostatic Hyperplasia" ,
 "Benzodiazepine Withdrawal" ,
 "Biliary Cirrhosis" ,
 "Binge Eating Disorde" ,
 "Bipolar Disorde" ,
 "Birth Control" ,
 "Bladder Infection" ,
 "Bleeding Disorde" ,
 "Blepharitis" ,
 "Body Dysmorphic Disorde" ,
 "Bone infection" ,
 "Borderline Personality Disorde" ,
 "Bowel Preparation" ,
 "Breakthrough Pain" ,
 "Breast Cance" ,
 "Breast Cancer, Adjuvant" ,
 "Breast Cancer, Metastatic" ,
 "Breast Cancer, Palliative" ,
 "Breast Cancer, Prevention" ,
 "Bronchitis" ,
 "Bronchospasm Prophylaxis" ,
 "Bulimia" ,
 "Bullous Pemphigoid" ,
 "Burning Mouth Syndrome" ,
 "Burns, External" ,
 "Bursitis" ,
 "Cachexia" ,
 "cal Segmental Glomerulosclerosis" ,
 "Cance" ,
 "Cataplexy" ,
 "Cerebral Edema" ,
 "Cerebral Spasticity" ,
 "Cervical Dystonia" ,
 "Chlamydia Infection" ,
 "Chronic Fatigue Syndrome" ,
 "Chronic Idiopathic Constipation" ,
 "Chronic Inflammatory Demyelinating Polyradiculoneuropathy" ,
 "Chronic Lymphocytic Leukemia" ,
 "Chronic Myelogenous Leukemia" ,
 "Chronic Myofascial Pain" ,
 "Chronic Pain" ,
 "Chronic Pancreatitis" ,
 "Chronic Spasticity" ,
 "Clostridial Infection" ,
 "Cluster Headaches" ,
 "CMV Prophylaxis" ,
 "Coccidioidomycosis" ,
 "Cold Sores" ,
 "Cold Symptoms" ,
 "Colorectal Cance" ,
 "Computed Tomography" ,
 "condition" ,
 "Condylomata Acuminata" ,
 "Conjunctivitis" ,
 "Conjunctivitis, Allergic" ,
 "Conjunctivitis, Bacterial" ,
 "Constipation" ,
 "Constipation, Acute" ,
 "Constipation, Chronic" ,
 "Constipation, Drug Induced" ,
 "COPD" ,
 "COPD, Acute" ,
 "COPD, Maintenance" ,
 "Corneal Refractive Surgery" ,
 "Coronary Artery Disease" ,
 "Costochondritis" ,
 "Cough" ,
 "Cough and Nasal Congestion" ,
 "Crohn's Disease" ,
 "Crohn's Disease, Acute" ,
 "Crohn's Disease, Maintenance" ,
 "Cutaneous Candidiasis" ,
 "Cutaneous T-cell Lymphoma" ,
 "Cyclic Vomiting Syndrome" ,
 "Cyclitis" ,
 "Cyclothymic Disorde" ,
 "Cystic Fibrosis" ,
 "Dandruff" ,
 "Deep Neck Infection" ,
 "Deep Vein Thrombosis" ,
 "Deep Vein Thrombosis Prophylaxis after Hip Replacement Surgery" ,
 "Deep Vein Thrombosis, First Event" ,
 "Deep Vein Thrombosis, Prophylaxis" ,
 "Deep Vein Thrombosis, Recurrent Event" ,
 "Dementia" ,
 "Dental Abscess" ,
 "Depression" ,
 "Dercum's Disease" ,
 "Dermatitis" ,
 "Dermatologic Lesion" ,
 "Dermatological Disorders" ,
 "Dermatomyositis" ,
 "Dermatophytosis" ,
 "Diabetes Insipidus" ,
 "Diabetes, Type 1" ,
 "Diabetes, Type 2" ,
 "Diabetic Kidney Disease" ,
 "Diabetic Macular Edema" ,
 "Diabetic Peripheral Neuropathy" ,
 "Diagnosis and Investigation" ,
 "Diaper Rash" ,
 "Diarrhea" ,
 "Diarrhea, Acute" ,
 "Diarrhea, Chronic" ,
 "Dietary Fiber Supplementation" ,
 "Dietary Supplementation" ,
 "Dissociative Identity Disorde" ,
 "Diverticulitis" ,
 "Dry Eye Disease" ,
 "Dry Skin" ,
 "Dumping Syndrome" ,
 "Duodenal Ulce" ,
 "Dupuytren's contracture" ,
 "Dysautonomia" ,
 "Dyspareunia" ,
 "Dystonia" ,
 "Dysuria" ,
 "Ear Wax Impaction" ,
 "Eczema" ,
 "Edema" ,
 "Ehrlichiosis" ,
 "emale Infertility" ,
 "Emergency Contraception" ,
 "Endometrial Cance" ,
 "Endometrial Hyperplasia" ,
 "Endometriosis" ,
 "Enterocolitis" ,
 "Eosinophilic Esophagitis" ,
 "Epididymitis, Sexually Transmitted" ,
 "Epilepsy" ,
 "Erectile Dysfunction" ,
 "Erosive Esophagitis" ,
 "Esophageal Variceal Hemorrhage Prophylaxis" ,
 "eve" ,
 "Expectoration" ,
 "Extrapyramidal Reaction" ,
 "Eye Redness" ,
 "Eye Redness/Itching" ,
 "Eyelash Hypotrichosis" ,
 "Gallbladder Disease" ,
 "Gas" ,
 "Gastric Ulcer Maintenance Treatment" ,
 "Gastritis/Duodenitis" ,
 "Gastroenteritis" ,
 "Gastrointestinal Decontamination" ,
 "Gastrointestinal Hemorrhage" ,
 "Gastrointestinal Stromal Tum" ,
 "Gastroparesis" ,
 "ge (amlodipine / valsartan)" ,
 "Gender Dysphoria" ,
 "Generalized Anxiety Disorde" ,
 "GERD" ,
 "Giant Cell Tumor of Bone" ,
 "Giardiasis" ,
 "Gingivitis" ,
 "Glaucoma" ,
 "Glaucoma, Open Angle" ,
 "Glioblastoma Multi" ,
 "Glioblastoma Multiforme" ,
 "Gonadotropin Inhibition" ,
 "Gonococcal Infection, Uncomplicated" ,
 "Gout" ,
 "Gout, Acute" ,
 "Gouty Arthritis" ,
 "Hashimoto's disease" ,
 "Head and Neck Cance" ,
 "Head Injury" ,
 "Head Lice" ,
 "Headache" ,
 "Heart Attack" ,
 "Heart Failure" ,
 "Helicobacter Pylori Infection" ,
 "Hemophilia A" ,
 "Hemophilia B" ,
 "Hemorrhoids" ,
 "Hemorrhoids (pramoxine / zinc oxide)" ,
 "Hepatic Encephalopathy" ,
 "Hepatitis B" ,
 "Hepatitis C" ,
 "Hepatocellular Carcinoma" ,
 "Herbal Supplementation" ,
 "Hereditary Angioedema" ,
 "Herpes Simplex" ,
 "Herpes Simplex Dendritic Keratitis" ,
 "Herpes Simplex, Mucocutaneous/Immunocompetent Host" ,
 "Herpes Simplex, Mucocutaneous/Immunocompromised Host" ,
 "Herpes Simplex, Suppression" ,
 "Herpes Zoste" ,
 "Herpes Zoster, Prophylaxis" ,
 "Hiccups" ,
 "Hidradenitis Suppurativa" ,
 "High Blood Pressure" ,
 "High Cholesterol" ,
 "High Cholesterol, Familial Heterozygous" ,
 "High Cholesterol, Familial Homozygous" ,
 "Hirsutism" ,
 "Histoplasmosis" ,
 "HIV Infection" ,
 "Hot Flashes" ,
 "Human Papilloma Virus" ,
 "Human Papillomavirus Prophylaxis" ,
 "Hypercalcemia of Malignancy" ,
 "Hyperekplexia" ,
 "Hyperhidrosis" ,
 "Hyperkalemia" ,
 "Hyperlipoproteinemia" ,
 "Hyperlipoproteinemia Type IIa, Elevated LDL" ,
 "Hyperphosphatemia" ,
 "Hyperphosphatemia of Renal Failure" ,
 "Hyperprolactinemia" ,
 "Hypersomnia" ,
 "Hypertensive Emergency" ,
 "Hyperthyroidism" ,
 "Hypertriglyceridemia" ,
 "Hypoactive Sexual Desire Disorde" ,
 "Hypocalcemia" ,
 "Hypodermoclysis" ,
 "Hypoestrogenism" ,
 "Hypogonadism, Male" ,
 "Hypokalemic Periodic Paralysis" ,
 "Hypomagnesemia" ,
 "Hypoparathyroidism" ,
 "Hypotension" ,
 "Hypothyroidism, After Thyroid Removal" ,
 "ibrocystic Breast Disease" ,
 "ibromyalgia" ,
 "Ichthyosis" ,
 "ICU Agitation" ,
 "Idiopathic Thrombocytopenic Purpura" ,
 "Immunosuppression" ,
 "Impetig" ,
 "Indigestion" ,
 "Infection Prophylaxis" ,
 "Inflammatory Bowel Disease" ,
 "Inflammatory Conditions" ,
 "Influenza" ,
 "Influenza Prophylaxis" ,
 "Insomnia" ,
 "Insomnia, Stimulant-Associated" ,
 "Insulin Resistance Syndrome" ,
 "Intermittent Claudication" ,
 "Interstitial Cystitis" ,
 "Intraabdominal Infection" ,
 "Intraocular Hypertension" ,
 "Iritis" ,
 "Iron Deficiency Anemia" ,
 "Irritable Bowel Syndrome" ,
 "Ischemic Stroke" ,
 "Ischemic Stroke, Prophylaxis" ,
 "Jet Lag" ,
 "Joint Infection" ,
 "Juvenile Idiopathic Arthritis" ,
 "Juvenile Rheumatoid Arthritis" ,
 "Keratitis" ,
 "Keratoconjunctivitis Sicca" ,
 "Keratosis" ,
 "Kidney Infections" ,
 "Labor Induction" ,
 "Labor Pain" ,
 "Lactation Augmentation" ,
 "Lactose Intolerance" ,
 "Left Ventricular Dysfunction" ,
 "Lennox-Gastaut Syndrome" ,
 "Leukemia" ,
 "lic Acid Deficiency" ,
 "Lichen Planus" ,
 "Lichen Sclerosus" ,
 "Light Anesthesia" ,
 "Light Sedation" ,
 "Lipodystrophy" ,
 "Liver Magnetic Resonance Imaging" ,
 "llicle Stimulation" ,
 "Local Anesthesia" ,
 "Lyme Disease" ,
 "Lyme Disease, Erythema Chronicum Migrans" ,
 "Lyme Disease, Neurologic" ,
 "Lymphocytic Colitis" ,
 "Lymphoma" ,
 "m Pain Disorde" ,
 "Macular Degeneration" ,
 "Macular Edema" ,
 "Major Depressive Disorde" ,
 "Malaria" ,
 "Malaria Prevention" ,
 "mance Anxiety" ,
 "Mania" ,
 "Mantle Cell Lymphoma" ,
 "me" ,
 "Melanoma" ,
 "Melanoma, Metastatic" ,
 "Melasma" ,
 "Meniere's Disease" ,
 "Meningococcal Meningitis Prophylaxis" ,
 "Menopausal Disorders" ,
 "Menorrhagia" ,
 "Menstrual Disorders" ,
 "Methicillin-Resistant Staphylococcus Aureus Infection" ,
 "Migraine" ,
 "Migraine Prevention" ,
 "Mild Cognitive Impairment" ,
 "min / saxagliptin)" ,
 "min / sitagliptin)" ,
 "min)" ,
 "mist (" ,
 "Mitral Valve Prolapse" ,
 "Mixed Connective Tissue Disease" ,
 "Mononucleosis" ,
 "moterol / mometasone)" ,
 "moterol)" ,
 "Motion Sickness" ,
 "Mountain Sickness / Altitude Sickness" ,
 "Mucositis" ,
 "mulation) (phenylephrine)" ,
 "Multiple Myeloma" ,
 "Multiple Sclerosis" ,
 "Muscle Pain" ,
 "Muscle Spasm" ,
 "Myasthenia Gravis" ,
 "Mycobacterium avium-intracellulare, Treatment" ,
 "Mycoplasma Pneumonia" ,
 "Myelodysplastic Syndrome" ,
 "Myelofibrosis" ,
 "Myeloproliferative Disorders" ,
 "Myotonia Congenita" ,
 "Narcolepsy" ,
 "Nasal Carriage of Staphylococcus aureus" ,
 "Nasal Congestion" ,
 "Nasal Polyps" ,
 "Nausea (phosphorated carbohydrate solution)" ,
 "Nausea/Vomiting" ,
 "Nausea/Vomiting of Pregnancy" ,
 "Nausea/Vomiting, Chemotherapy Induced" ,
 "Nausea/Vomiting, Postoperative" ,
 "Neck Pain" ,
 "Nephrotic Syndrome" ,
 "Neuralgia" ,
 "Neuropathic Pain" ,
 "Neutropenia" ,
 "Neutropenia Associated with Chemotherapy" ,
 "New Daily Persistent Headache" ,
 "Night Terrors" ,
 "Nightmares" ,
 "Nocturnal Leg Cramps" ,
 "Non-Hodgkin's Lymphoma" ,
 "Noninfectious Colitis" ,
 "Nonoccupational Exposure" ,
 "Non-Small Cell Lung Cance" ,
 "Not Listed / Othe" ,
 "NSAID-Induced Gastric Ulce" ,
 "Obesity" ,
 "Obsessive Compulsive Disorde" ,
 "Obstructive Sleep Apnea/Hypopnea Syndrome" ,
 "Occipital Neuralgia" ,
 "Occupational Exposure" ,
 "Oligospermia" ,
 "Onychomycosis, Fingernail" ,
 "Onychomycosis, Toenail" ,
 "Oophorectomy" ,
 "Ophthalmic Surgery" ,
 "Opiate Adjunct" ,
 "Opiate Dependence" ,
 "Opiate Withdrawal" ,
 "Opioid Overdose" ,
 "Opioid-Induced Constipation" ,
 "Oppositional Defiant Disorde" ,
 "Oral and Dental Conditions" ,
 "Oral Thrush" ,
 "Organ Transplant, Rejection Prophylaxis" ,
 "Organ Transplant, Rejection Reversal" ,
 "Osteoarthritis" ,
 "Osteolytic Bone Lesions of Multiple Myeloma" ,
 "Osteolytic Bone Metastases of Solid Tumors" ,
 "Osteoporosis" ,
 "Otitis Externa" ,
 "Otitis Media" ,
 "Ovarian Cance" ,
 "Ovarian Cysts" ,
 "Overactive Bladde" ,
 "Ovulation Induction" ,
 "Paget's Disease" ,
 "Pain" ,
 "Pain/Feve" ,
 "Pancreatic Cance" ,
 "Pancreatic Exocrine Dysfunction" ,
 "Panic Disorde" ,
 "Paranoid Disorde" ,
 "Parkinsonism" ,
 "Parkinson's Disease" ,
 "Pe" ,
 "Pediatric Growth Hormone Deficiency" ,
 "Pelvic Inflammatory Disease" ,
 "Pemphigoid" ,
 "Pemphigus" ,
 "Peptic Ulce" ,
 "Percutaneous Coronary Intervention" ,
 "Performance Anxiety" ,
 "Perimenopausal Symptoms" ,
 "Period Pain" ,
 "Periodic Limb Movement Disorde" ,
 "Periodontitis" ,
 "Perioral Dermatitis" ,
 "Peripheral Arterial Disease" ,
 "Peripheral Neuropathy" ,
 "Peritonitis" ,
 "Persistent Depressive Disorde" ,
 "Pertussis" ,
 "Pertussis Prophylaxis" ,
 "Pharyngitis" ,
 "Photoaging of the Skin" ,
 "Pinworm Infection (Enterobius vermicularis)" ,
 "Pityriasis rubra pilaris" ,
 "Plaque Psoriasis" ,
 "Platelet Aggregation Inhibition" ,
 "Pneumococcal Disease Prophylaxis" ,
 "Pneumonia" ,
 "Polycystic Ovary Syndrome" ,
 "Polycythemia Vera" ,
 "Polymyositis/Dermatomyositis" ,
 "Post Traumatic Stress Disorde" ,
 "Post-Cholecystectomy Diarrhea" ,
 "Postherpetic Neuralgia" ,
 "Postmenopausal Symptoms" ,
 "Postoperative Increased Intraocular Pressure" ,
 "Postoperative Ocular Inflammation" ,
 "Postoperative Pain" ,
 "Postpartum Depression" ,
 "Postural Orthostatic Tachycardia Syndrome" ,
 "Precocious Puberty" ,
 "Pre-Exposure Prophylaxis" ,
 "Premature Ejaculation" ,
 "Premature Lab" ,
 "Premature Ventricular Depolarizations" ,
 "Premenstrual Dysphoric Disorde" ,
 "Premenstrual Syndrome" ,
 "Prevention of Bladder infection" ,
 "Prevention of Cardiovascular Disease" ,
 "Prevention of Dental Caries" ,
 "Prevention of Hypokalemia" ,
 "Prevention of Osteoporosis" ,
 "Prevention of Thromboembolism in Atrial Fibrillation" ,
 "Primary Hyperaldosteronism" ,
 "Primary Immunodeficiency Syndrome" ,
 "Primary Nocturnal Enuresis" ,
 "Primary Ovarian Failure" ,
 "Progesterone Insufficiency" ,
 "Prostate Cance" ,
 "Prostatitis" ,
 "Pruritus" ,
 "Pseudobulbar Affect" ,
 "Pseudotumor Cerebri" ,
 "Psoriasis" ,
 "Psoriatic Arthritis" ,
 "Psychosis" ,
 "Pudendal Neuralgia" ,
 "Pulmonary Edema" ,
 "Pulmonary Embolism" ,
 "Pulmonary Embolism, First Event" ,
 "Pulmonary Hypertension" ,
 "Pupillary Dilation" ,
 "Radionuclide Myocardial Perfusion Study" ,
 "Rat-bite Feve" ,
 "Raynaud's Syndrome" ,
 "Reflex Sympathetic Dystrophy Syndrome" ,
 "Renal Cell Carcinoma" ,
 "Renal Tubular Acidosis" ,
 "Restless Legs Syndrome" ,
 "Reversal of Nondepolarizing Muscle Relaxants" ,
 "Reversal of Opioid Sedation" ,
 "Rheumatoid Arthritis" ,
 "Rhinitis" ,
 "Rhinorrhea" ,
 "Rosacea" ,
 "Salmonella Gastroenteritis" ,
 "Sarcoidosis" ,
 "Scabies" ,
 "Schilling Test" ,
 "Schizoaffective Disorde" ,
 "Schizophrenia" ,
 "Schnitzler Syndrome" ,
 "Sciatica" ,
 "Seasonal Affective Disorde" ,
 "Seasonal Allergic Conjunctivitis" ,
 "Seborrheic Dermatitis" ,
 "Secondary Hyperparathyroidism" ,
 "Sedation" ,
 "Seizure Prevention" ,
 "Seizures" ,
 "Sexual Dysfunction, SSRI Induced" ,
 "Shift Work Sleep Disorde" ,
 "Sinus Symptoms" ,
 "Sinusitis" ,
 "Sjogren's Syndrome" ,
 "Skin and Structure Infection" ,
 "Skin Cance" ,
 "Skin Disinfection, Preoperative" ,
 "Skin or Soft Tissue Infection" ,
 "Skin Rash" ,
 "Small Bowel or Pancreatic Fistula" ,
 "Smoking Cessation" ,
 "Social Anxiety Disorde" ,
 "Soft Tissue Sarcoma" ,
 "Somat" ,
 "Sore Throat" ,
 "Spondyloarthritis" ,
 "Spondylolisthesis" ,
 "Squamous Cell Carcinoma" ,
 "Status Epilepticus" ,
 "Steroid Responsive Inflammatory Conditions" ,
 "Still's Disease" ,
 "Stomach Cance" ,
 "Stomach Ulce" ,
 "Strabismus" ,
 "Strep Throat" ,
 "Streptococcal Infection" ,
 "Stress Ulcer Prophylaxis" ,
 "Strongyloidiasis" ,
 "Subarachnoid Hemorrhage" ,
 "Submental Fullness" ,
 "Sunburn" ,
 "Supraventricular Tachycardia" ,
 "Surgical Prophylaxis" ,
 "Swine Flu" ,
 "Syringomyelia" ,
 "Systemic Lupus Erythematosus" ,
 "Systemic Mastocytosis" ,
 "Systemic Sclerosis" ,
 "Temporomandibular Joint Disorde" ,
 "Tendonitis" ,
 "Thrombocythemia" ,
 "Thromboembolic Stroke Prophylaxis" ,
 "Thyroid Cance" ,
 "Thyrotoxicosis" ,
 "tic (mycophenolic acid)" ,
 "Tinea Corporis" ,
 "Tinea Cruris" ,
 "Tinea Pedis" ,
 "Tinea Versicol" ,
 "Tinnitus" ,
 "Tonsillitis/Pharyngitis" ,
 "Topical Disinfection" ,
 "Tourette's Syndrome" ,
 "Transient Ischemic Attack" ,
 "Traveler's Diarrhea" ,
 "Trichomoniasis" ,
 "Trichotillomania" ,
 "Trigeminal Neuralgia" ,
 "TSH Suppression" ,
 "Tuberculosis, Latent" ,
 "Tympanostomy Tube Placement Surgery" ,
 "Ulcerative Colitis" ,
 "Ulcerative Colitis, Active" ,
 "Ulcerative Colitis, Maintenance" ,
 "Ulcerative Proctitis" ,
 "Underactive Thyroid" ,
 "Undifferentiated Connective Tissue Disease" ,
 "Upper Limb Spasticity" ,
 "Upper Respiratory Tract Infection" ,
 "Urinary Incontinence" ,
 "Urinary Retention" ,
 "Urinary Tract Infection" ,
 "Urinary Tract Stones" ,
 "Urticaria" ,
 "Uterine Bleeding" ,
 "Uterine Fibroids" ,
 "Uveitis" ,
 "Uveitis, Posteri" ,
 "Vaginal Yeast Infection" ,
 "Varicella-Zoste" ,
 "Ventricular Arrhythmia" ,
 "Ventricular Fibrillation" ,
 "Ventricular Tachycardia" ,
 "Vertig" ,
 "Vitamin B12 Deficiency" ,
 "Vitamin D Deficiency" ,
 "Vitamin/Mineral Supplementation and Deficiency" ,
 "Vitamin/Mineral Supplementation during Pregnancy/Lactation" ,
 "von Willebrand's Disease" ,
 "Vulvodynia" ,
 "Warts" ,
 "Wegener's Granulomatosis" ,
 "Weight Loss" ,
 "Wolff-Parkinson-White Syndrome" ,
 "Women (oxybutynin)" ,
 "Xerostomia" ,
 "Yellow Fever Prophylaxis" ,
 "zen Shoulde" ,
 "Zollinger-Ellison Syndrome" ,


    ]
    return render_template('index.html', conditions=conditions)

@app.route("/analyze/<condition>", methods=["GET"])
def analyze(condition):
    try:
        top = data[data['condition'] == condition][['drugName', 'usefulness']].sort_values(by='usefulness', ascending=False)
        top = top.drop_duplicates(subset=['drugName']).head(10).reset_index(drop=True)
        return render_template('results.html', condition=condition, drugs=top.to_dict(orient='records'))
    except KeyError:
        return render_template('error.html', error_message='Condition not found')
@app.route("/analyze", methods=["POST"])
def recommended_medicines():
    condition = request.form.get("condition")
    if not condition:
        return render_template('error.html', error_message='Condition not provided')
    
    recommended_medicines_list = recommend_medicines_by_condition(condition, data, num_recommendations=10)
    if recommended_medicines_list == "No data available for this condition.":
        return render_template('error.html', error_message='Condition not found in data')
    
    return render_template('results.html', recommended_medicines=recommended_medicines_list)



def recommend_medicines_by_condition(condition, data, num_recommendations=5):
    condition_data = data[data['condition'] == condition]
    
    if condition_data.empty:
        return "No data available for this condition."
    
    avg_usefulness_by_drug = condition_data.groupby('drugName')['usefulness'].mean()
    recommended_medicines = avg_usefulness_by_drug.nlargest(num_recommendations).index.tolist()
    
    return recommended_medicines


if __name__ == "__main__":
    app.run(debug=True)
